language:
    - c

git:
  depth: 1

matrix:
    include:
        - env: CONFIGURE=""
        - env: CONFIGURE="--enable-debug"
        - env: CONFIGURE="--disable-nancy"
        - env: CONFIGURE="--disable-mouse"
        - env: CONFIGURE="--disable-external"
        - env: CONFIGURE="--enable-iplookup"
        - env: CONFIGURE="--enable-proxy"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq intltool libgtk2.0-dev libnotify-dev libx11-dev libltdl-dev

script:
    - ./autogen.sh
    - ./configure --disable-silent-rules $CONFIGURE
    - make CFLAGS="-Wall -Werror" CXXFLAGS="-Wall -Werror"
